rbd::Joint Class Reference
rbd::Joint Class Reference
Joint representation.
#include <Joint.h>
Public Types
enum Type {
Rev,
Prism,
Spherical,
Planar,
Cylindrical,
Free,
Fixed
}
Joint type.
enum OldType {
RevX,
RevY,
RevZ,
PrismX,
PrismY,
PrismZ
}
Old joint type for Api compatibility.
Public Member Functions
Joint ()
Joint (OldType type, bool forward, std::string name)
Compatibility constructor.
Joint (Type type, const Eigen::Vector3d &axis, bool forward, std::string name)
Joint (Type type, bool forward, std::string name)
Type type () const
double direction () const
bool forward () const
void forward (bool forward)
int params () const
Number of parameters of the joint.
int dof () const
Number of degree of freedom of the joint.
const std::string & name () const
const Eigen::Matrix< double,
6, Eigen::Dynamic > & motionSubspace () const
template<typename T >
sva::PTransform< T > pose (const std::vector< T > &q) const
Compute the joint transformation from predecessor to successor frame.
sva::MotionVecd motion (const std::vector< double > &alpha) const
Compute the joint velocity.
sva::MotionVecd tanAccel (const std::vector< double > &alphaD) const
Compute the tangential part of the acceleration S*alphaD.
std::vector< double > zeroParam () const
std::vector< double > zeroDof () const
sva::PTransformd sPose (const std::vector< double > &q) const
Safe version of pose method.
sva::MotionVecd sMotion (const std::vector< double > &alpha) const
Safe version of motion method.
sva::MotionVecd sTanAccel (const std::vector< double > &alphaD) const
Safe version of tanAccel method.
bool operator== (const Joint &b) const
bool operator!= (const Joint &b) const
Static Public Member Functions
static std::vector< double > ZeroParam (Type type)
static std::vector< double > ZeroDof (Type type)
Detailed Description
Joint representation.
Hold joint name (used as identifier) and compute transformation, speed and motion subspace. WARNING : Free joint translation parameters are in FP coordinate (Example 4.5 p81).
Member Enumeration Documentation
enum rbd::Joint::OldType
Old joint type for Api compatibility.
Enumerator
RevX
Revolute joint about X axis.
RevY
Revolute joint about Y axis.
RevZ
Revolute joint about Z axis.
PrismX
Prismatique joint about X axis.
PrismY
Prismatique joint about Y axis.
PrismZ
Prismatique joint about Z axis.
enum rbd::Joint::Type
Joint type.
Enumerator
Rev
Revolute joint about an user specified axis.
Prism
Prismatique joint about an user specified axis.
Spherical
Spherical joint, represented by a quaternion.
Planar
Planar joint (2 prismatic(X, Y) and 1 revolute(Z)).
Cylindrical
Cylindrical joint (Z prismatic, Z revolute).
Free
Free joint, represented by a quaternion.
Fixed
Fixed joint.
Constructor & Destructor Documentation
rbd::Joint::Joint () inline
rbd::Joint::Joint (OldType type, bool forward, std::string name) inline
Compatibility constructor.
Parameters
type Joint type.
forward Joint is in forward direction if true.
name Joint name, must be unique in a multibody.
References Fixed, Prism, PrismX, PrismY, PrismZ, Rev, RevX, RevY, and RevZ.
rbd::Joint::Joint (Type type, const Eigen::Vector3d & axis, bool forward, std::string name) inline
Parameters
type Joint type.
axis User specified.
forward Joint is in forward direction if true.
name Joint name must be unique in a multibody.
rbd::Joint::Joint (Type type, bool forward, std::string name) inline
Parameters
type Joint type.
forward Joint is in forward direction if true.
name Joint name, must be unique in a multibody.
Member Function Documentation
double rbd::Joint::direction () const inline
Returns
Joint direction.
int rbd::Joint::dof () const inline
Number of degree of freedom of the joint.
Returns
Number of generalized speed and acceleration variable.
bool rbd::Joint::forward () const inline
Returns
true if joint is forward, else false.
void rbd::Joint::forward (bool forward) inline
Parameters
forward Put the joint in forward direction if true.
sva::MotionVecd rbd::Joint::motion (const std::vector< double > & alpha) const inline
Compute the joint velocity.
Parameters
alpha vector of generalized speed variable.
Returns
Spatial motion vector of the joint.
References Cylindrical, Fixed, Free, Planar, Prism, Rev, and Spherical.
Referenced by sMotion().
const Eigen::Matrix<double, 6, Eigen::Dynamic>& rbd::Joint::motionSubspace () const inline
Returns
Joint motion subspace in successor frame coordinate.
const std::string& rbd::Joint::name () const inline
Returns
Joint name.
Referenced by rbd::operator<<().
bool rbd::Joint::operator!= (const Joint & b) const inline
bool rbd::Joint::operator== (const Joint & b) const inline
int rbd::Joint::params () const inline
Number of parameters of the joint.
Returns
Number of generalized position variable.
template<typename T > sva::PTransform< T > rbd::Joint::pose (const std::vector< T > & q) const inline
Compute the joint transformation from predecessor to successor frame.
Parameters
q vector of generalized position variable.
Returns
Spatial transformation from predecessor to successor frame.
References Cylindrical, Fixed, Free, sva::PTransform< T >::inv(), Planar, Prism, rbd::QuatToE(), Rev, sva::RotZ(), and Spherical.
Referenced by sPose().
sva::MotionVecd rbd::Joint::sMotion (const std::vector< double > & alpha) const inline
Safe version of motion method.
See Also
motion
Exceptions
std::domain_error If the number of generalized speed variable is wrong.
References motion().
sva::PTransformd rbd::Joint::sPose (const std::vector< double > & q) const inline
Safe version of pose method.
See Also
pose
Exceptions
std::domain_error If the number of generalized position variable is wrong.
References pose().
sva::MotionVecd rbd::Joint::sTanAccel (const std::vector< double > & alphaD) const inline
Safe version of tanAccel method.
See Also
tanAccel
Exceptions
std::domain_error If the number of generalized acceleration variable is wrong.
References tanAccel().
sva::MotionVecd rbd::Joint::tanAccel (const std::vector< double > & alphaD) const inline
Compute the tangential part of the acceleration S*alphaD.
Parameters
alphaD vector of generalized acceleration variable.
Returns
Tangential part of acceleration
References Cylindrical, Fixed, Free, Planar, Prism, Rev, and Spherical.
Referenced by sTanAccel().
Type rbd::Joint::type () const inline
Returns
Joint type.
std::vector< double > rbd::Joint::zeroDof () const inline
Returns
Joint velocity at zero.
References ZeroDof().
std::vector< double > rbd::Joint::ZeroDof (Type type) inline static
Returns
Joint velocity at zero.
References Cylindrical, Fixed, Free, Planar, Prism, Rev, and Spherical.
Referenced by zeroDof().
std::vector< double > rbd::Joint::zeroParam () const inline
Returns
Joint configuation at zero.
References ZeroParam().
std::vector< double > rbd::Joint::ZeroParam (Type type) inline static
Returns
Joint configuation at zero.
References Cylindrical, Fixed, Free, Planar, Prism, Rev, and Spherical.
Referenced by zeroParam().