#!/bin/bash
#
# Setup NAG
#
. `dirname $0`/../common.sh

build_dir=`mktemp -d`
trap "rm -rf -- '$build_dir'" EXIT

# Setup environment variables.
export LD_LIBRARY_PATH="$install_dir/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$install_dir/lib/`dpkg-architecture -qDEB_BUILD_MULTIARCH`:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH="$install_dir/lib/pkgconfig:$PKG_CONFIG_PATH"
export PKG_CONFIG_PATH="$install_dir/lib/`dpkg-architecture -qDEB_BUILD_MULTIARCH`/pkgconfig:$PKG_CONFIG_PATH"

# Checkout NAG.
cd "$build_dir"
wget "http://www.nag.co.uk/downloads/impl/cll6i25dcl.tgz"
tar xzvf cll6i25dcl.tgz
./install.sh -accept -installdir="$install_dir/NAG"
